name: sqflite_migration
description: A library to enable sqlite db migrations, using sqflite plugin.
version: 0.3.0
homepage: https://github.com/flutterings/sqflite_migration

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  matcher: ^0.12.10

flutter:
